-- comment

/*
SELECT column1,column2,....

FROM table_name

SELECT CUST_NAME,CUST_EMAIL,CUST_CITY
FROM CUSTOMERS;


--WHERE BOOLEAN COND IS SMF


SELECT CUST_NAME,CUST_EMAIL,CUST_CITY
FROM CUSTOMERS
WHERE CUST_EMAIL IS NULL;

SELECT CUST_NAME
FROM CUSTOMERS
WHERE CUST_EMAIL IS NOT NULL;


--------------------------------------------------------

SELECT CUST_NAME
FROM CUSTOMERS
WHERE CUST_STATE = 'IL';


SELECT CUST_NAME
FROM CUSTOMERS
WHERE CUST_COUNTRY='USA';
-- AND OR
SELECT CUST_NAME
FROM CUSTOMERS
WHERE 
  CUST_COUNTRY='USA' 
  AND CUST_EMAIL IS NOT NULL 
  AND CUST_STATE = 'IL';

SELECT CUST_ID,CUST_ADDRESS
FROM CUSTOMERS
WHERE 
  CUST_COUNTRY='AFRICA' 
  AND CUST_EMAIL IS NULL; 
  

--SELECT COLUMN 'USER FRIENDLY NAME'

SELECT CUST_NAME "USER NAME", CUST_EMAIL "MULO"
FROM CUSTOMERS;

SELECT CUSTOMERS.CUST_NAME "NIK",CUST_STATE "sHTAT"
FROM CUSTOMERS
WHERE CUSTOMERS.CUST_EMAIL IS NOT NULL
ORDER BY CUSTOMERS.CUST_STATE;
*/

SELECT VENDORS.VEND_NAME "NAME"
FROM VENDORS
WHERE VENDORS.VEND_STATE IS NOT NULL;

SELECT COUNT(*) "COUNT OF REC"
FROM VENDORS
WHERE VEND_STATE IS NOT NULL;

SELECT COUNT(*) "COUNT OF ENGLISH"
FROM VENDORS
WHERE VEND_COUNTRY='England';

SELECT VENDORS.VEND_NAME "pOSTAVSHIC", PRODUCTS.PROD_NAME "PRODUCT"
FROM VENDORS,PRODUCTS
WHERE VENDORS.VEND_ID = PRODUCTS.VEND_ID;

SELECT CUSTOMERS.CUST_NAME"Name",
  ORDERS.ORDER_DATE"Order date",
  ORDERITEMS.QUANTITY"kOL-VO",
  PRODUCTS.PROD_NAME"nAZVA",
  VENDORS.VEND_NAME
    
FROM CUSTOMERS,ORDERS,ORDERITEMS,PRODUCTS,VENDORS
WHERE 
  CUSTOMERS.CUST_ID = ORDERS.CUST_ID
  AND ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
  AND ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
  AND PRODUCTS.VEND_ID = VENDORS.VEND_ID;




