Select VENDORS.VEND_ADDRESS 
FROM VENDORS;

SELECT DISTINCT VENDORS.VEND_ADDRESS 
FROM VENDORS;

SELECT DISTINCT VENDORS.VEND_ADDRESS
FROM VENDORS;

SELECT COUNT(X) 
FROM 
  (SELECT DISTINCT VENDORS.VEND_ADDRESS X FROM VENDORS) MYTABLE;
  

SELECT A.COUNT_OF_VENDORS-B.COUNT_OF_UNIC
FROM

  (SELECT COUNT(*) COUNT_OF_VENDORS
  FROM VENDORS) A,

  (SELECT COUNT(*)COUNT_OF_UNIC
  FROM
  (SELECT DISTINCT VENDORS.VEND_ADDRESS X FROM VENDORS)) B;
  
select x.count_of_email-y.count_of_unic_e
from
  (Select count(CUST_ID)count_of_email
  from CUSTOMERS)x,
  (select count(*) count_of_unic_e
    from
      (select distinct CUSTOMERS.CUST_EMAIL 
      FROM CUSTOMERS 
      where CUSTOMERS.CUST_EMAIL is not null))y;
      
      
select x.num_of_orders-y.orders 
from
  (select count(ORDER_NUM) num_of_orders
  from orders)x,
  (select count(*) orders
  from
    (select ORDERS.CUST_ID
    from ORDERS)) y;
    
select CUSTOMERS.CUST_NAME,ORDERS.ORDER_NUM
  from CUSTOMERS,ORDERS
  where CUSTOMERS.CUST_ID=ORDERS.CUST_ID;
  
SELECT
  CUSTOMERS.CUST_NAME,
  ORDERS.ORDER_NUM
FROM
  CUSTOMERS JOIN ORDERS ON CUSTOMERS.CUST_ID=ORDERS.CUST_ID;
  
SELECT
  CUSTOMERS.CUST_NAME,
  PRODUCTS.PROD_NAME,
  RODUCTS.Q
  
FROM
  VENDORS JOIN PRODUCTS ON PRODUCTS.VEND_ID=VENDORS.VEND_ID;

SELECT
  CUSTOMERS.CUST_NAME,
  PRODUCTS.PROD_NAME
FROM 
  CUSTOMERS 
  JOIN ORDERS 
    ON CUSTOMERS.CUST_ID=ORDERS.CUST_ID
  JOIN ORDERITEMS
    ON ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM
  JOIN PRODUCTS
    ON PRODUCTS.PROD_ID=ORDERITEMS.PROD_ID;


SELECT ORDERS.ORDER_NUM,SUM(ORDERITEMS.QUANTITY)
FROM
  ORDERS JOIN ORDERITEMS
  ON ORDERS.ORDER_NUM=ORDERITEMS.ORDER_NUM
  
GROUP BY ORDERS.ORDER_NUM;

SELECT CUSTOMERS.CUST_NAME, COUNT(ORDERS.ORDER_NUM)
FROM 
  CUSTOMERS JOIN ORDERS 
  ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
GROUP BY CUSTOMERS.CUST_NAME;

SELECT VEND_NAME
FROM
  (SELECT VENDORS.VEND_NAME ,COUNT(PRODUCTS.PROD_NAME)COUNT_OF
  FROM
    VENDORS JOIN PRODUCTS
    ON VENDORS.VEND_ID = PRODUCTS.VEND_ID
  GROUP BY VENDORS.VEND_NAME)X
WHERE X.COUNT_OF<3;


----ORDERS PRICE
SELECT CUSTOMERS.CUST_NAME,ALL_ORD_SUMS
FROM
CUSTOMERS JOIN

(SELECT CUSTOMERS.CUST_ID,SUM(ORD_SUM)ALL_ORD_SUMS

FROM
  CUSTOMERS 
  JOIN
  ORDERS
  ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
  JOIN
    (SELECT ORDERS.ORDER_NUM, SUM(ORDERITEMS.QUANTITY * ORDERITEMS.ITEM_PRICE)ORD_SUM
    FROM
      ORDERS JOIN ORDERITEMS 
      ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
  
    GROUP BY ORDERS.ORDER_NUM)TABLE_ORD_PRICE
  ON TABLE_ORD_PRICE.ORDER_NUM = ORDERS.ORDER_NUM
  
GROUP BY CUSTOMERS.CUST_ID) FILTER

ON CUSTOMERS.CUST_ID=FILTER.CUST_ID




